# Use an official node runtime as a parent image
FROM node:14

# Set the working directory in the container
WORKDIR /IdeaProjects

# Add the current directory contents into the container at /app
ADD .idea ./test-demo-app/.idea
